#!/bin/sh
set -e
#DEBHELPER#
if [ "$1" = "configure" ]; then
	ldconfig
fi

echo ""
echo "
  두벌식 글판이란?

   - 닿소리 (자음) 한 벌,
     홀소리 (모음) 한 벌을
     서로 다른 글쇠 자리에 나누어 놓은 한글 글판이다.
"
sleep 2
echo "
  세벌식 글판이란?

   - 첫소리     (초성) 한 벌,
     가운뎃소리 (중성) 한 벌,
     끝소리     (종성) 한 벌을
     서로 다른 글쇠 자리에 나누어 놓은 한글 글판이다.
"
sleep 2
echo ""
